/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_special_AndroidSmartUpdates_helper_PatchHelper */

#ifndef _Included_com_special_AndroidSmartUpdates_helper_PatchHelper
#define _Included_com_special_AndroidSmartUpdates_helper_PatchHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_special_AndroidSmartUpdates_helper_PatchHelper
 * Method:    applyPatch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT jint JNICALL Java_com_lewa_bl_Tools_ApkUtils_applyPatch
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
